# jmx_exporter_config.yml
startDelaySeconds: 0
hostPort: 127.0.0.1:9010
beans:
  - Jvm:
      - type: "java.lang<type=OperatingSystem>.*"
      - type: "java.lang<type=Memory>.*"
      - type: "java.lang<type=GarbageCollector,name=*>.*"
      - type: "java.lang<type=Threading>.*"
  - Catalina:
      - type: "Catalina<type=GlobalRequestProcessor,name=*>.*"
      - type: "Catalina<type=ThreadPool,name=*>.*"
