global:
  scrape_interval: 15s # 모든 타겟에 대해 15초마다 스크랩

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'nginx-exporter'
    static_configs:
      - targets: ['nginx-exporter:9113'] # docker-compose 서비스 이름

  - job_name: 'tomcat-jmx'
    static_configs:
      - targets: ['tomcat1:9010', 'tomcat2:9011'] # tomcat1, tomcat2 서비스의 JMX Exporter 포트

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100'] # docker-compose 서비스 이름
